### ISSUE TITLE
Analyze Security Threats

### ISSUE THREAD

**Issue by nathan-wick** [nathan-wick/nutrition-ai#10]
Because we will be storing confidential data, it is important that we throughly analyze possible security threats to prevent malicious activity.

**Comment by EmileeSchweitzer** [comment]
.

**Comment by EmileeSchweitzer** [comment]
https://www.dhs.gov/science-and-technology/cybersecurity-mobile-app-security
https://www.guardsquare.com/

**Comment by EmileeSchweitzer** [comment]
Firebase Incorporations for Security 
--------------------------------------------------------
https://firebase.google.com/support/privacy#:~:text=Security%20information,-Data%20encryption&text=Firebase%20services%20encrypt%20data%20in,Cloud%20Functions%20for%20Firebase

Google uses Firebase Service Data in accordance with our [privacy policy](https://policies.google.com/privacy) and applicable terms. Firebase Service Data is used, for example, to:

- Provide Firebase services you request
- Make recommendations to optimize use of Firebase services
- Maintain and improve Firebase services
- Provide and improve other services you request
- Understand your use of Firebase and other Google services
- Provide better support to and communicate with you
- Protect you, our users, the public and Google
- Comply with legal obligations

**Comment by EmileeSchweitzer** [comment]
Firebase makes it straightforward to gather and track users' preferences around collection and processing data:

- Set up privacy settings
- Update your app to use privacy settings
- Track changes in privacy settings

**Comment by EmileeSchweitzer** [comment]
https://www.section.io/engineering-education/how-to-secure-firebase-apps-with-firebase-security-rules/

Secure logged-in user data
The logged-in user data should always be protected. With this security rule, users can only update their data if they are autheniticated successfully.

You could use a 2-factor authentication (2FA) for enhanced security. For instance, you can use an email for verification using auth.token.email_verified

**Comment by EmileeSchweitzer** [comment]
https://console.firebase.google.com/project/nathan-wick-nutrition-ai/features/all
