### ISSUE TITLE
Store Meal Data

### ISSUE THREAD

**Issue by nathan-wick** [nathan-wick/nutrition-ai#33]
We need to find a database of meals that includes recipes and ingredients. Then, store the meal data in our database and link the meal ingredients.

**Comment by nathan-wick** [comment]
Would it be possible to combine the `Meals starting with...` collections into one collection named `meals`? This would make the information easier to use in the future. Other than that, this looks perfect!


![Image](https://github.com/nathan-wick/nutrition-ai/assets/27981761/2daf6404-b5fe-4198-bd1d-342a7ee4f3ba)

**Comment by patel5r4** [comment]
> Would it be possible to combine the `Meals starting with...` collections into one collection named `meals`? This would make the information easier to use in the future. Other than that, this looks perfect!
> 
> ![Image](https://user-images.githubusercontent.com/27981761/273285826-2daf6404-b5fe-4198-bd1d-342a7ee4f3ba.png)


Done! Added all the meals to a single collection named "Meals":

![image](https://github.com/nathan-wick/nutrition-ai/assets/72940661/80ca2dd5-8510-46c2-a8a0-f28c6d30aaed)

**Comment by nathan-wick** [comment]
Awesome! Looks great :)
