### ISSUE TITLE
Create Recommendations View Prototype

### ISSUE THREAD

**Issue by nathan-wick** [nathan-wick/nutrition-ai#6]
We will need to be able to display our meal recommendations to the user. Creating a prototype for this view will help us visualize it before we code it.

**Comment by ModupeD** [comment]
@nathan-wick can i do this?

**Comment by nathan-wick** [comment]
@ModupeD Absolutely!

**Comment by ModupeD** [comment]
This is the design, Here is a link to the file:

[Figma Design File](https://www.figma.com/file/jg2tBGUYWbZUhHGKz3rI8c/Senior-Design?type=design&node-id=101%3A12&mode=design&t=5ttYN8R04ggC86jt-1)

![Image](https://github.com/nathan-wick/nutrition-ai/assets/69601432/09517db0-39c2-4dcb-8bae-80e975e8ba83)
